### ISSUE TITLE
[GDPR 18] Verification through municipal census to access minor spaces as a minor without guardianship

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/decidim-module-kids#44]
Ref: GDPR 18

**Is your feature request related to a problem? Please describe.**

For some of the bodies that Barcelona City Council currently has, it is also necessary to allow access by minors under 16 years of age (minors without guardianship). At the legal level, it is no longer necessary to ask for parental consent for these participants.

Logic of access to the space:
- Add a checkbox within the configuration of a "Space for minors" that says "I want to check the age with the municipal census" and where you can put the maximum age of the users. This option will be available when the  verification method supports this logic.
     - When a participant accesses this space, and is not a minor's account (ref GDPR10), they should be asked to verify their age.
     - When the participant does not have an age associated with their user account, access will not be allowed.

- Verification logic with the AJBCN municipal census:
     - When the municiapl census verifies that I am under 16 years of age, it will store my age encrypted in the database.

**Describe the solution you'd like**
So, in order to comply with this behaviour, we need to create a specific verifier that have the correct metadata and can check the of the person. 

**Acceptance criteria**
- [ ] As a participant, when I try to access a space for minors, I am required to verify my age using the municipal census. If I don't meet the requierments I won't be allowed to access.
- [x] As a minor participant, I can access to a minors space. 
- [x] As a minor without guardianship participant, I can access to a minors space when it's enabled.

**Comment by NilHomedes** [comment]
Hi @fblupi @rxnetwalker 

Part of this issue was solved on #36 

But, there's one AC that was not included in this PR, this one:
 
 - [ ] As a participant, when I try to access a space for minors, I am required to verify my age using the municipal census. If I don't meet the requierments I won't be allowed to access.

So, in order to improve the current PX, we should have this AC done. 

To specify a little more, we want that:
- [ ] When a participant try to aces to a space for minors a pop-up is displayed. The modal should be the same that appears when you try to do an action restricted by permissions. 
- [ ] The text in the modal should be "In order to access to a minor's space you must be under `minimum_adult_age`, please verify your age, so that we can confirm that you can access" 

See example: 


![Image](https://user-images.githubusercontent.com/71442847/223711407-67c581f8-00b2-49d5-8668-9ad29188a64f.png)

**Comment by fblupi** [comment]
@NilHomedes if the user has been already authorized but doesn't meet the requirements needed to access the participatory process the modal shouldn't be displayed. Isn't it?

**Comment by fblupi** [comment]
@NilHomedes showing a modal is not viable here. We could make it but we would need to change a lot of code and it would take so much time and make the module harder to maintain. I propose an easier way to do it by changing the flash message instead of showing the modal.

There are four conditions here:
1. The user is not logged in
2. The user is logged in but has not been authorized through the authorization method specified in the configuration
3. The user is logged in and has been authorized, but doesn't meet the requirements of age configured
4. The user is logged in, has been authorized, and meets the requirements of age configured

For condition 1, the user is redirected to the login page and shows an alert message:

<img width="754" alt="Screenshot 2023-03-13 at 16 02 50" src="https://user-images.githubusercontent.com/6973564/224745756-2af7573a-9ed6-45c1-9663-f1937e496f51.png">

 For conditions 2 and 3, the user is redirected back with an alert message:

<img width="754" alt="Screenshot 2023-03-13 at 16 04 32" src="https://user-images.githubusercontent.com/6973564/224746020-e0b8d1b3-c0b2-4b28-8dd0-fcb86d3f6dd9.png">

<img width="752" alt="Screenshot 2023-03-13 at 16 03 42" src="https://user-images.githubusercontent.com/6973564/224745997-3c3b2ab3-86b0-4084-87ad-1ab050774789.png">

For condition 4, the user access to the participatory space successfully.

**Comment by NilHomedes** [comment]
Ok, I agree with your solution @fblupi 

Sorry for the delay answering.
